name: dartkart

description: >
   dartkart is a framwork for web cartografy in the tradition of the
   JavaScript libraries OpenLayers and Leaflet. It is neither a 1:1 port
   nor does it provide the full functionality of either of them,
   but it has a similar structure and borrows a lot of ideas from them.

version: 0.0.5+2

authors:
  - Karl Guggisberg <karl.guggisberg@guggis.ch>

dependencies:
   browser: '>=0.10.0 <0.11.0'
   args: '>=0.13.0 <0.14.0'

dev_dependencies:
  unittest: 0.5.9
